// export const products = {
//     ghk: {
//         id: 1,
//         name: "GHK-Cu",
//         subtitle: "Copper Peptide",
//         price: 69,
//         image: "assets/ghk-1.png",
//     },

//     ss31: {
//         id: 2,
//         name: "SS:31",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/ss-1.png",
//     },
//     tb500: {
//         id: 3,
//         name: "TB500",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/tb-1.png",
//     },
//     kis: {
//         id: 4,
//         name: "Kisspetin",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/kis-1.png",
//     },
//     ret: {
//         id: "5",
//         name: "Retatrutide",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/ret-1.png",
//     },
//     sem: {
//         id: "6",
//         name: "Semaglutide",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/sem-1.png",
//     },
//     pt141: {
//         id: "7",
//         name: "PT141",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/pt-1.png",
//     },
//     kpv: {
//         id: "8",
//         name: "KPV",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/kp-1.png",
//     },
//     nad: {
//         id: "9",
//         name: "Nad+",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/nad-1.png",
//     },
//     tes: {
//         id: "10",
//         name: "Tesamorelin",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/tes-1.png",
//     },
//     slu: {
//         id: "11",
//         name: "SLU_PP",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/slu-1.png",
//     },
//     ipa: {
//         id: "12",
//         name: "Ipamorelin",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/ipa-1.png",
//     },
//     tir: {
//         id: "13",
//         name: "Tirzepatide",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/tir-1.png",
//     },
//     amin: {
//         id: "14",
//         name: "5-AMINO-1MQ",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/ami-1.png",
//     },
//     mel: {
//         id: "15",
//         name: "Melanotan",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/mel-1.png",
//     },
//     cic: {
//         id: "16",
//         name: "CIC-1295",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/cic-1.png",
//     },
//     epi: {
//         id: "17",
//         name: "Epithalon",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/epi-1.png",
//     },
//     aod: {
//         id: "18",
//         name: "AOD-9604",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/aod-1.png",
//     },
//     thy: {
//         id: "19",
//         name: "Thymulin",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/thy-1.png",
//     },
//     mot: {
//         id: "20",
//         name: "MOTS-c",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/mot-1.png",
//     },
//     bac: {
//         id: "21",
//         name: "Bac.water",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/bac-1.png",
//     },
//     bpc: {
//         id: "22",
//         name: "BPC-157",
//         subtitle: "Mitochondrial Peptide",
//         price: 99,
//         image: "assets/bpc-1.jpg",
//     },
// };



export const products = [
    {
        id: 1,
        slug: "ghk-cu",
        name: "GHK-Cu",
        subtitle: "Copper Peptide",
        price: 69,
        image: "/assets/ghk-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 2,
        slug: "ss-31",
        name: "SS-31",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/ss-1.png",
        desc: "Mitochondrial support peptide",
    },
    {
        id: 3,
        slug: "tb-500",
        name: "TB-500",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/tb-1.png",
        desc: "Recovery & repair peptide",
    },
    {
        id: 4,
        slug: "kisspetin",
        name: "Kisspetin",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/kis-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 5,
        slug: "retatrutide",
        name: "Retatrutide",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/ret-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 6,
        slug: "semaglutide",
        name: "Semaglutide",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/sem-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 7,
        slug: "pt-141",
        name: "PT141",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/pt-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 8,
        slug: "kpv",
        name: "KPV",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/kp-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 9,
        slug: "nad+",
        name: "NAD+",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/nad-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 10,
        slug: "tesamorelin",
        name: "Tesamorelin",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/tes-1.png",
        desc: "Metabolism support peptide",
    },
    {
        id: 11,
        slug: "slu-pp-322",
        name: "SLU-PP-322",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/slu-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 12,
        slug: "ipamorelin",
        name: "Ipamorelin",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/ipa-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 13,
        slug: "tirzepatide",
        name: "Tirzepatide",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/tir-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 14,
        slug: "5-amino-1mq",
        name: "5-AMINO-1MQ",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/ami-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 15,
        slug: "melanotan",
        name: "Melanotan",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/mel-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 16,
        slug: "cjc-1295",
        name: "CJC-1295",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/cic-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 17,
        slug: "epithalon",
        name: "Epithalon",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/epi-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 18,
        slug: "aod-9604",
        name: "AOD-9604",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/aod-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 19,
        slug: "thymulin",
        name: "Thymulin",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/thy-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 20,
        slug: "mots-c",
        name: "MOTS-c",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/mot-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 21,
        slug: "bac-water",
        name: "Bac.water",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/bac-1.png",
        desc: "Skin & recovery support peptide",
    },
    {
        id: 22,
        slug: "bpc-157",
        name: "BPC-157",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "/assets/bpc-1.jpg",
        desc: "Skin & recovery support peptide",
    },
];