export const products = {
    ghk: {
        id: 1,
        name: "GHK-Cu",
        subtitle: "Copper Peptide",
        price: 69,
        image: "assets/ghk-1.png",
    },

    ss31: {
        id: 2,
        name: "SS:31",
        subtitle: "Mitochondrial Peptide",
        price: 79,
        image: "assets/ss-1.png",
    },
    tb500: {
        id: 3,
        name: "TB500",
        subtitle: "Mitochondrial Peptide",
        price: 59,
        image: "assets/tb-1.png",
    },
    kis: {
        id: 4,
        name: "Kisspetin",
        subtitle: "Mitochondrial Peptide",
        price: 49,
        image: "assets/kis-1.png",
    },
    ret: {
        id: "5",
        name: "Retatrutide",
        subtitle: "Mitochondrial Peptide",
        price: 39,
        image: "assets/ret-1.png",
    },
    sem: {
        id: "6",
        name: "Semaglutide",
        subtitle: "Mitochondrial Peptide",
        price: 29,
        image: "assets/sem-1.png",
    },
    pt141: {
        id: "7",
        name: "PT141",
        subtitle: "Mitochondrial Peptide",
        price: 19,
        image: "assets/pt-1.png",
    },
    kpv: {
        id: "8",
        name: "KPV",
        subtitle: "Mitochondrial Peptide",
        price: 99,
        image: "assets/kp-1.png",
    },
    nad: {
        id: "9",
        name: "Nad+",
        subtitle: "Mitochondrial Peptide",
        price: 109,
        image: "assets/nad-1.png",
    },
    tes: {
        id: "10",
        name: "Tesamorelin",
        subtitle: "Mitochondrial Peptide",
        price: 19,
        image: "assets/tes-1.png",
    },
    slu: {
        id: "11",
        name: "SLU_PP",
        subtitle: "Mitochondrial Peptide",
        price: 109,
        image: "assets/slu-1.png",
    },
    ipa: {
        id: "12",
        name: "Ipamorelin",
        subtitle: "Mitochondrial Peptide",
        price: 209,
        image: "assets/ipa-1.png",
    },
    tir: {
        id: "13",
        name: "Tirzepatide",
        subtitle: "Mitochondrial Peptide",
        price: 139,
        image: "assets/tir-1.png",
    },
    amin: {
        id: "14",
        name: "5-AMINO-1MQ",
        subtitle: "Mitochondrial Peptide",
        price: 299,
        image: "assets/ami-1.png",
    },
    mel: {
        id: "15",
        name: "Melanotan",
        subtitle: "Mitochondrial Peptide",
        price: 129,
        image: "assets/mel-1.png",
    },
    cic: {
        id: "16",
        name: "CIC-1295",
        subtitle: "Mitochondrial Peptide",
        price: 189,
        image: "assets/cic-1.png",
    },
    epi: {
        id: "17",
        name: "Epithalon",
        subtitle: "Mitochondrial Peptide",
        price: 189,
        image: "assets/epi-1.png",
    },
    aod: {
        id: "18",
        name: "AOD-9604",
        subtitle: "Mitochondrial Peptide",
        price: 189,
        image: "assets/aod-1.png",
    },
    thy: {
        id: "19",
        name: "Thymulin",
        subtitle: "Mitochondrial Peptide",
        price: 189,
        image: "assets/thy-1.png",
    },
    mot: {
        id: "20",
        name: "MOTS-c",
        subtitle: "Mitochondrial Peptide",
        price: 189,
        image: "assets/mot-1.png",
    },
    bac: {
        id: "21",
        name: "Bac.water",
        subtitle: "Mitochondrial Peptide",
        price: 189,
        image: "assets/bac-1.png",
    },
    bpc: {
        id: "22",
        name: "BPC-157",
        subtitle: "Mitochondrial Peptide",
        price: 389,
        image: "assets/bpc-1.jpg",
    },
};